### ISSUE TITLE
Is this module superseded or deprecated?

### ISSUE THREAD

**Issue by andrewwakeling** [christophercliff/watch-ignore-webpack-plugin#6]
I just noticed that there is an in-built module which does this. The source code looks very similar and has more recent changes.

Am I right to assume that this module is now superseded or deprecated in favour of the in-built one?
https://github.com/webpack/docs/wiki/list-of-plugins

If so, can this be made clear in the README.md.

**Comment by bobby-brennan** [comment]
+1, I confused this repo with the official WebpackIgnorePlugin.  Please add a deprecation notice or a clarification to the README.

**Comment by andrewwakeling** [comment]
Thank you!
